### ISSUE TITLE
prototype 3 , 5 ,11 , 15 

### ISSUE THREAD

**Issue by alire7a** [alire7a/Tesla#3]
نمایه
بروز رسانی نمایه
رویداد
تصویر

لطفا فایل های مربوط رو اینجا اپلود کنید

**Comment by Sabashafieii** [comment]
[faz1-saba shafiei (4).zip](https://github.com/alire7a/Tesla/files/11234261/faz1-saba.shafiei.4.zip)

**Comment by Soroooush** [comment]
[](url)

**Comment by Soroooush** [comment]
> نمایه بروز رسانی نمایه رویداد تصویر
> 
> لطفا فایل های مربوط رو اینجا اپلود کنید

[faz1_980122680095_Soroush-Gholizadeh.zip](https://github.com/alire7a/Tesla/files/11278055/faz1_980122680095_Soroush-Gholizadeh.zip)
