### ISSUE TITLE
prototype 1 , 2 , 4, 7

### ISSUE THREAD

**Issue by alire7a** [alire7a/Tesla#4]
لطفا فایل های مربوط رو اپلود کنید

**Comment by siavashbis** [comment]
![7](https://user-images.githubusercontent.com/91088578/232046405-0286b553-a3e3-4454-9034-f7a080639342.png)
![1 1](https://user-images.githubusercontent.com/91088578/232046433-d1c8bb5b-b861-4a4a-bbb7-6937e16bd754.png)
![1 2](https://user-images.githubusercontent.com/91088578/232046443-df8b9b67-e9ef-4034-96e4-0c4684fdbd81.png)
![2](https://user-images.githubusercontent.com/91088578/232046449-82a484da-1539-445d-8242-a6bf346dabd8.png)
![4](https://user-images.githubusercontent.com/91088578/232046452-07483927-0986-4d64-838b-61eefd571d1d.png)
